---
crawler_memlimit: 4G
crawler_hash_workers: 64
crawler_file_workers: 12
crawler_directory_workers: 4
crawler_version: 213d9509ff7ab7ba8061d5228ad4092c50253fa4
amqp_message_ttl: 4h
golang_version: 1.18.2
ipfs_version: 0.17.0
ipfs_memlimit: 12G
ipfs_hard_disable_swapping: true
sniffer_head_count: 12
sniffer_memlimit: 24G
sniffer_lastseen_prunelen: 10485760
sniffer_lastseen_expiration: 12h
rabbitmq_memlimit: 16G
tika_extractor_version: "1.1"
tika_extractor_sha256: cb8237013f8e2de9d2efd23d04c2392c640476e805493a6939b89ef89ad05b6d
tika_extractor_heap_max: 3072m
influxdb_backup_destination: "{{ storagebox_mountpoint }}/influxdb"
influxdb_backup_user: "{{ lookup('env', 'USER') }}"
influxdb_backup_bucket: "telegraf"
storagebox_mountpoint_group: "{{ lookup('env', 'USER') }}"
nsfw_server_port: 3432
nsfw_server_version: e903037676d4b721e67f6d2273b8a193a0a21bd7
node_branch: node_16.x
nyats_port: 9614
nyats_version: thumbnail_server_fixups
ipfs_search_api_port: 9615
ipfs_search_api_version: 456551f5361153d336938e4b3d6c27a673f3133a
pinservice_version: e91ffc12d90653c8285b655d6b69d6da0429b198
pinservice_port: 7070
