---
- name: Install Influxdata repository key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present
- name: Add Influxdata repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} stable"
    filename: "influxdata"
    state: present
- name: Install InfluxDB
  apt:
    pkg: influxdb2
    state: present
- name: Install InfluxDB configuration
  template:
    src: config.yml
    dest: /etc/influxdb/config.yml
  notify: restart influxdb
