---
- hosts: aux
  become: true
  roles:
    - role: adamruzicka.wireguard
      tags: ['wireguard']
      vars:
        wireguard_networks:
          - wg0
- import_playbook: monitoring.yml
- import_playbook: observability.yml

