---
# aux host role; anything that's not properly distributed yet: bservability, sniffer, rabbitmq
- hosts: aux
  become: true
  roles:
    - role: adamruzicka.wireguard
      tags: ['wireguard']
      vars:
        wireguard_networks:
          - wg0
- import_playbook: monitoring.yml
- import_playbook: observability.yml
- import_playbook: rabbitmq.yml
- import_playbook: sniffer.yml
