---
- hosts: backend
  become: true
  vars:
    - es_heap_size: 20g
    - ipfs_memlimit: 12G
    - crawler_memlimit: 4G
  roles:
    - { name: cgconfig, tags: ['cgconfig']}
    - { name: elasticsearch, tags: ['elasticsearch']}
    - { name: snapshots, tags: ['snapshots'] }
    - { name: rabbitmq, tags: ['rabbitmq'] }
    - { name: ipfs, tags: ['ipfs'] }
    - { name: ipfs-tika, tags: ['ipfs-tika'] }
    - { name: crawler, tags: ['crawler'] }
    - { name: snifloop, tags: ['snifloop']}
    - { name: nginx, tags: ['nginx']}
    - { name: api, tags: ['api']}
