---
- hosts: backend
  become: true
  vars:
    - es_heap_size: 16g
    - ipfs_memlimit: 12G
    - crawler_memlimit: 4G
    - golang_version: 1.14.4
  roles:
    - { name: golang, tags: ['golang']}
    - { name: disable-eth-offloading, tags: ['disable-eth-offloading']}
    - { name: cgconfig, tags: ['cgconfig']}
    - { name: elasticsearch, tags: ['elasticsearch']}
    - { name: rabbitmq, tags: ['rabbitmq'] }
    - { name: ipfs, tags: ['ipfs'] }
    - { name: ipfs-tika, tags: ['ipfs-tika'] }
    - { name: crawler, tags: ['crawler'] }
    - { name: sniffer, tags: ['sniffer'] }
    - { name: nginx, tags: ['nginx']}
    - { name: api, tags: ['api']}
    - { name: storagebox, tags: ['storagebox'] }
    - { name: snapshots, tags: ['snapshots'] }
    - { name: ipfs-cluster, tags: ['ipfs-cluster']}
