---
- hosts: elasticsearch
  become: true
  vars_files:
    - common_variables.yml
  roles:
    - role: elasticsearch
      tags: ['elasticsearch']
      vars:
        oss_version: true
        es_log_dir: "/var/log/elasticsearch"
        es_data_dirs:
          - "/var/lib/elasticsearch"
        es_plugins:
          - plugin: repository-s3
        es_config:
          cluster.name: ipfs-search
          node.name: "{{ inventory_hostname }}"
          node.attr.zone_id: "{{ zone_id }}"
          cluster.routing.allocation.awareness.attributes: zone_id
          discovery.seed_hosts: "{% for host in groups['elasticsearch'] if host != inventory_hostname %}{{ hostvars[host].vlan_ip | ipaddr('address') }}{% if not loop.last %}, {% endif %}{% endfor %}"
          network.publish_host: "{{ vlan_ip | ipaddr('address')}}"
          # Only during bootstrapping
          # https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-bootstrap-cluster.html
          cluster.initial_master_nodes: "{{ groups['master'] }}"
          repositories.url.allowed_urls: ["http://localhost:8080/*"]
          network.host: ["_local_", "_site_"]
          node.data: "{{ inventory_hostname in groups['index'] }}"
          node.master: "{{ inventory_hostname in groups['master'] }}"
    - { name: snapshots, tags: ['snapshots'] }
