---
- hosts: frontend
  become: true
  vars_files:
    - common_variables.yml
  vars:
    # Note: manually disable certbot testing from the command line!
    # Example:
    # ansible-playbook -e certbot_test=false frontend.yml
    - certbot_test: true
  roles:
    - { name: nginx, tags: ['nginx']}
    - { name: frontend, tags: ['frontend']}
    - { name: certbot , tags: ['certbot']}
