---
- hosts: frontend
  become: true
  vars:
    - certbot_email: info@ipfs-search.com
    - certbot_domains: ipfs-search.com,api.ipfs-search.com
    # Note: manually disable certbot testing from the command line!
    - certbot_test: true
  roles:
    - { name: nginx, tags: ['nginx']}
    - { name: frontend, tags: ['frontend']}
    - { name: certbot , tags: ['certbot']}
