---
- hosts: index
  become: true
  vars_files:
    - common_variables.yml
  roles:
    - role: elasticsearch
      tags: ['elasticsearch']
      vars:
        oss_version: true
        es_log_dir: "/var/log/elasticsearch"
        es_data_dirs:
          - "/var/lib/elasticsearch"
        es_plugins:
          - plugin: repository-s3
        es_config:
          cluster.name: ipfs-search
          node.name: "{{ inventory_hostname }}"
          discovery.seed_hosts: "{% for host in groups['index'] if host != inventory_hostname %}{{ hostvars[host].vlan_ip | ipaddr('address') }}{% if not loop.last %}, {% endif %}{% endfor %}"
          network.publish_host: "{{ vlan_ip | ipaddr('address')}}"
          # Only during bootstrapping
          # https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-bootstrap-cluster.html
          # cluster.initial_master_nodes: "{{ groups['index'] }}"
          repositories.url.allowed_urls: ["http://localhost:8080/*"]
          network.host: ["_local_", "_site_"]
          node.data: true
          node.master: true
          reindex.remote.whitelist: 172.16.34.1:9200
    - { name: tika-extractor, tags: ['tika-extractor'] }
    - { name: crawler, tags: ['crawler'] }
    - { name: nginx, tags: ['nginx']}
    - { name: api, tags: ['api']}
    - { name: storagebox, tags: ['storagebox'] }
    - { name: snapshots, tags: ['snapshots'] }
