---
# Common configuration for all hosts
- hosts: all
  become: true
  strategy: free
  vars_files:
    - vars/common.yml
  roles:
    - role: journald
      tags: ['journald']
    - role: rsyslog
      tags: ['rsyslog']
    - role: telegraf
      tags: ['telegraf']
