- name: install loki
  hosts: caminer
  gather_facts: yes
  become: yes
  roles:
    - name: loki installation
      role: loki
      vars:
        # loki_data_path: /var/lib/loki 
        ## be careful there!
