---
- hosts: aux
  become: true
  vars_files:
    - common_variables.yml
  vars:
    influxdb2_http_bind_address: "{{ vlan_ip | ipaddr('address')}}:8086"
  roles:
    - { name: influxdb2, tags: influxdb }
    - { name: storagebox, tags: ['storagebox'] }
    - { name: influxdb_backup, tags: influxdb_backup }
