-
  name: Promtail Setup
  hosts: allen
  # ^
  # |
  # testing on a single host from the AUX group
  become: yes
  tasks:
    - name: Update apt repo and cache on all Ubuntu box
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    - name: Install needed packages
      apt:
        name: [ unzip, curl ]
        state: present
        update_cache: yes
    - name: Install Promtail Loki
      shell: |
        cd /opt
        curl https://api.github.com/repos/grafana/loki/releases/latest | grep -E "browser_download_url" | grep promtail-linux-amd64 | cut -d '"' -f 4 | wget -qi -
        unzip promtail-linux-amd64.zip
        mv promtail-linux-amd64 /usr/local/bin/promtail
    - name: Create conf directory
      file:
        state: directory
        path: /etc/promtail
    - name: Create data directory
      file:
        state: directory
        path: /data/promtail
    - name: Create promtail config file
      template:
        src: ./templates/promtail/config.yml
        dest: /etc/promtail/config.yml
    - name: add monitoring server IP to config file
      lineinfile:
        path: /etc/promtail/config.yml
        regexp: '^(.*)<client_url>(.*)$'
        line: '  - url: http://172.16.34.1:3100/loki/api/v1/push'
        backrefs: yes
        # ^
        # |
        # TODO: variable here
    - name: Create systemd unit
      template:
        src: ./templates/promtail/promtail.service
        dest: /etc/systemd/system/promtail.service
    - name: Systemd setup for loki
      systemd:
        daemon_reload: yes
        name: promtail
        enabled: yes
        state: started
