---
- hosts: all
  become: true
  gather_facts: no
  pre_tasks:
    - name: 'Apt updates'
      raw: sudo apt-get update
    - name: 'Install python2'
      raw: sudo apt-get -y install python-simplejson
