---
roles:
  - name: golang
    src: gantsign.golang
    version: 2.10.2
collections:
  - name: ansible.netcommon
    version: 2.4.0
  - name: community.hrobot
    version: 1.5.2
  - name: hetzner.hcloud
    version: 1.8.2
