---
- name: wireguard
  src: adamruzicka.wireguard
  version: 42d5d43c8d70295c723c81024e17e6c9f2de085a
- name: golang
  src: gantsign.golang
  version: 2.8.5
- name: elasticsearch
  src: elastic.elasticsearch
  version: v7.12.0
- name: netcommon
  src: ansible.netcommon
  version: 2.4.0
- name: hrobot
  src: community.hrobot
