---
# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -l hellman setup_hetzner.yml
# - name: Install OS image
#   hosts: all
#   user: root
#   gather_facts: no
#   tasks:
#     - name: Installing system image
#       command: /root/.oldroot/nfs/install/installimage -r yes -l 0 -i /root/.oldroot/nfs/install/../images/Ubuntu-2004-focal-64-minimal.tar.gz -g -t yes -G yes -a
#     - reboot:
#         reboot_timeout: 3600
#     # - name: Remove host key from known hosts
#     #   known_hosts:
#     #     name: "{{ ansible_host }}"
#     #     state: absent
#     #   delegate_to: localhost
# - name: Bootstrap
#   import_playbook: bootstrap.yml
# - name: Setup system
#   import_playbook: site.yml
- hosts: dmz
  order: sorted
  roles:
    - vlan_ips
