# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -l hellman setup_hetzner.yml
- name: Install OS image
  hosts: all
  user: root
  ignore_unreachable: yes
  tags: installimage
  tasks:
    - name: Make sure our inventory is super fresh
      meta: refresh_inventory
    - name: Installing system image
      command: /root/.oldroot/nfs/install/installimage -r yes -l 0 -i /root/.oldroot/nfs/install/../images/Ubuntu-2004-focal-64-minimal.tar.gz -g -t yes -G yes -a
      environment:
        TERM: xterm # Somehow, at least on one host, this is is necessary.
    - reboot:
        reboot_timeout: 7200
    # Watch out! Only on newly installed hosts!
    # - name: Remove host key from known hosts
    #   known_hosts:
    #     name: "{{ ansible_host }}"
    #     state: absent
    #   delegate_to: localhost

# - name: Bootstrap
#   import_playbook: bootstrap.yml
# - name: Setup system
#   import_playbook: site.yml
