# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook setup_hetzner.yml -l new
- name: Install OS image
  hosts: all # TODO: Filter by machines in rescue mode
  user: root
  ignore_unreachable: yes
  tags: install_image
  roles:
    - install_image
- name: Bootstrap
  import_playbook: bootstrap.yml
- name: Setup system
  import_playbook: site.yml
