---
# Common configuration for all hosts
- hosts: all
  become: true
  pre_tasks:
    - name: Install jmespath (local Ansible dependency for Elasticsearch)
      local_action: pip
      args:
        name: jmespath
      become: no
  vars:
    - hostname: "{{ inventory_hostname }}"
  roles:
    - { name: common, tags: ['common'] }
    - { name: hostname, tags: ['hostname']}
    - { name: unattended_upgrades, tags: ['upgrades']}
    - role: cgconfig
      tags: ['cgconfig']
    - role: telegraf
      tags: ['telegraf']
    - { name: firewall, tags: ['firewall']}
    - { name: jre, tags: ['jre']}
- hosts: dmz
  become: true
  roles:
    - role: vlan
      tags: ['vlan']
- import_playbook: elasticsearch.yml
# - import_playbook: ipfs.yml
# - import_playbook: index.yml
- import_playbook: api.yml
# - import_playbook: frontend.yml
