---
# Common configuration for all hosts
- hosts: all
  become: true
  pre_tasks:
    - name: Install jmespath (local Ansible dependency for Elasticsearch)
      local_action: pip
      args:
        name: jmespath
      become: no
  vars:
    - hostname: "{{ inventory_hostname }}"
  roles:
    - { name: common, tags: ['common'] }
    - { name: hostname, tags: ['hostname']}
- name: Backend
  import_playbook: backend.yml
- name: Frontend
  import_playbook: frontend.yml
