---
- hosts: elasticsearch
  become: true
  serial:
    - 1
    - 2
    - 20%
  any_errors_fatal: true
  vars_files:
    - vars/common.yml
  vars:
    snapshot_cron_host: "{{ groups['elasticsearch'] | first }}"
  roles:
    # - { name: ipfs-cluster, tags: ['ipfs-cluster'] }
    # - { name: storagebox, tags: ['storagebox'] }
    - { name: snapshots, tags: ['snapshots'] }
