---
- hosts: sniffer
  become: true
  vars_files:
    - common_variables.yml
  roles:
    - { name: disable-eth-offloading, tags: ['disable-eth-offloading']}
    - { name: cgconfig, tags: ['cgconfig']}
    - { name: elasticsearch, tags: ['elasticsearch']}
    - { name: rabbitmq, tags: ['rabbitmq'] }
    - { name: sniffer, tags: ['sniffer'] }
    - include_playbook: ipfs
    - { name: tika-extractor, tags: ['tika-extractor'] }
    - { name: crawler, tags: ['crawler'] }
    - { name: nginx, tags: ['nginx']}
    - { name: api, tags: ['api']}
    - { name: storagebox, tags: ['storagebox'] }
    - { name: snapshots, tags: ['snapshots'] }
