---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install apt upgrades
  apt:
    upgrade: dist
- name: Set timezone to Europe/Lisbon
  timezone:
    name: Europe/Lisbon
- name: Install misc utils
  apt:
    pkg:
      - apt-transport-https
      - screen
      - tree
      - git
      - software-properties-common # Includes add-apt-repository
      - jq
      - iotop
      - traceroute
      - man
      - smartmontools
      - psmisc
      - acl
    state: present
- name: Install scripts
  copy:
    dest: /usr/local/
    src: bin
    owner: root
    group: root
    mode: 0755
- name: Force default locale
  # Does away by endless LC_ALL warnings
  lineinfile:
    path: "{{ ansible_env.PWD }}/.pam_environment" # Workaround https://github.com/ansible/ansible/issues/15901
    regexp: "^LC_ALL="
    line: "LC_ALL=en_US.UTF-8"
    create: true
    mode: 0644
  become: false
