---
- name: Download binary
  get_url:
    url: https://github.com/grafana/loki/releases/download/{{ promtail_version }}/promtail-linux-amd64.zip
    dest: "/tmp/promtail-linux-amd64.zip"
    checksum: sha256:{{ promtail_download_sha256 }}
  register: promtail_download

- name: Unarchive promtail
  unarchive:
    copy: no
    src: "{{ promtail_download.dest }}"
    dest: /usr/local/bin
  when: promtail_download.changed
  notify: restart promtail

- name: Create conf directory
  file:
    state: directory
    path: /etc/promtail
    mode: '0755'

- name: Create data directory
  file:
    state: directory
    path: /var/lib/promtail
    mode: '0755'

- name: systemd unit
  template:
    src: promtail.service
    dest: /etc/systemd/system/promtail.service
    mode: 0644
  notify: restart promtail

- name: promtail config
  template:
    src: config.yml
    dest: /etc/promtail/config.yml
    mode: 0644
  notify:
    - restart promtail

- name: Add elasticsearch log files
  blockinfile:
    dest: /etc/promtail/config.yml
    block: |
      - job_name: elasticsearch_logs
        static_configs:
        - labels:
            hostname: ${HOSTNAME}
            job: elasticsearch_logs
            __path__: /var/log/elasticsearch/*.json

      - job_name: elasticsearch_gc
        static_configs:
        - labels:
            hostname: ${HOSTNAME}
            job: elasticsearch_gc
            __path__: /var/log/elasticsearch/gc.log
    backup: yes
  when: es_logs_to_loki
  notify:
    - restart promtail

- name: Systemd service enabled
  systemd:
    daemon_reload: yes
    name: promtail
    enabled: yes
    state: started

