---
- name: Download binary
  get_url:
    url: https://github.com/grafana/loki/releases/download/{{ promtail_version }}/promtail-linux-amd64.zip
    dest: "/tmp/promtail-linux-amd64.zip"
    checksum: sha256:{{ promtail_download_sha256 }}
  register: promtail_download

- name: Unarchive promtail
  unarchive:
    copy: no
    src: "{{ promtail_download.dest }}"
    dest: /usr/local/bin
  when: promtail_download.changed
  notify: restart promtail

- name: Create conf directory
  file:
    state: directory
    path: /etc/promtail
    mode: '0755'

- name: Create data directory
  file:
    state: directory
    path: /var/lib/promtail
    mode: '0755'

- name: systemd unit
  template:
    src: promtail.service
    dest: /etc/systemd/system/promtail.service
    mode: 0644
  notify: restart promtail

- name: promtail config
  template:
    src: config.yml
    dest: /etc/promtail/config.yml
    mode: 0644
  notify:
    - restart promtail

- name: Add custom logs files
  # lineinfile: 
  #   path: /etc/nginx/nginx.conf
  #   regexp: '^(.*)access_log(.*)$' 
  #   line: 'access_log /var/log/nginx/access.log anonymized;'
  #   backrefs: yes
  debug:
    msg: "{{ item }}"
  with_items:
      - "{{ log_files_paths }}"
  when: log_files_paths

- name: Systemd service enabled
  systemd:
    daemon_reload: yes
    name: promtail
    enabled: yes
    state: started

