---
- name: "User '{{ item.key }}' present"
  user:
    name: "{{ item.key }}"
    shell: /bin/bash
    state: present

- name: "SSH public key for '{{ item.key }}'"
  authorized_key:
    user: "{{ item.key }}"
    key: "{{ item.value }}"

- name: "'{{ item.key }}' in sudoers"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} ALL=(ALL:ALL) NOPASSWD: ALL"
    state: present
