---
- name: "User '{{ account.key }}' present"
  user:
    name: "{{ account.key }}"
    shell: /bin/bash
    state: present

- name: "SSH public key(s) for '{{ account.key }}'"
  authorized_key:
    user: "{{ account.key }}"
    key: "{{ account.value | join('\n') }}"
    exclusive: True

- name: "'{{ account.key }}' in sudoers"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ account.key }}"
    line: "{{ account.key }} ALL=(ALL:ALL) NOPASSWD: ALL"
    state: present
