- name: "Elasticsearch {{ snapshot_name }} daily snapshot cronjob on cron host"
  cron:
    name: "Elasticsearch {{ snapshot_name }} snapshot"
    cron_file: /etc/crontab
    minute: "16"
    hour: "{{ snapshot_hour }}"
    backup: yes
    user: nobody
    job: "/usr/local/bin/ipfs-search-snapshot-{{ snapshot_name }}.sh"
  delegate_to: "{{ snapshot_cron_host }}"
  run_once: True
- name: "Remove Elasticsearch {{ snapshot_name }} daily snapshot cronjob on other hosts"
  cron:
    cron_file: /etc/crontab
    name: "Elasticsearch {{ snapshot_name }} snapshot"
    state: absent
  when: inventory_hostname != snapshot_cron_host
