---
- name: Check snapshot repository
  uri:
    url: "http://127.0.0.1:9200/_snapshot/{{ snapshot_disk_name }}"
    status_code: 200, 404
  register: snapshot_check
- name: Create snapshot repository
  uri:
    url: "http://127.0.0.1:9200/_snapshot/{{ snapshot_disk_name }}"
    method: PUT
    body_format: json
    body: |
      {
        "type": "fs",
        "settings": {
          "location": "{{ snapshot_disk_path }}",
          "compress": true,
          "chunk_size": "524288000B"
        }
      }
  when: snapshot_check.status == 404
- name: Install snapshot script
  template:
    src: ipfs-search-snapshot.sh
    dest: /usr/local/bin/ipfs-search-snapshot-disk.sh
    mode: 0755
  vars:
    - snapshot_name: "{{ snapshot_disk_name }}"
- name: Elasticsearch daily disk snapshot cronjob
  cron:
    name: "Elasticsearch disk snapshot"
    cron_file: /etc/crontab
    minute: 16
    hour: 4
    backup: yes
    user: nobody
    job: "/usr/local/bin/ipfs-search-snapshot-disk.sh"
