---
- name: Check snapshot repository
  uri:
    url: "http://127.0.0.1:9200/_snapshot/{{ snapshot_disk_name }}"
    status_code: 200, 404
  register: snapshot_check
- name: Configure repository path in Elasticsearch
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: ^path.repo
    backup: yes
    line: "path.repo: [\"{{ snapshot_disk_path }}\"]"
    state: present
  register: repo_path
- name: Restart elasticsearch
  systemd: daemon_reload=yes state=restarted name=elasticsearch
  when: repo_path.changed
- name: Create snapshot repository
  uri:
    url: "http://127.0.0.1:9200/_snapshot/{{ snapshot_disk_name }}"
    method: PUT
    body_format: json
    body: |
      {
        "type": "fs",
        "settings": {
          "location": "{{ snapshot_disk_path }}",
          "compress": true,
          "chunk_size": "524288000B"
        }
      }
- name: Install snapshot script
  template:
    src: ipfs-search-snapshot.sh
    dest: /usr/local/bin/ipfs-search-snapshot-disk.sh
    mode: 0755
  vars:
    - snapshot_name: "{{ snapshot_disk_name }}"
- import_tasks: cron.yml
  vars:
    snapshot_hour: "4"
    snapshot_name: wasabi
