---
- name: Set SSH hostname
  set_fact:
    ssh_hostname: "{{ ansible_host | default(inventory_hostname) }}"
- name: Get new SSH host key
  command: "ssh-keyscan -t ecdsa-sha2-nistp256 {{ ssh_hostname }}"
  register: "host_keys"
  changed_when: false
- name: Add known_hosts for {{ inventory_hostname }}
  known_hosts:
    name: "{{ ssh_hostname }}"
    key: "{{ item }}"
  with_items: "{{ host_keys.stdout_lines | list }}"
