---
- name: build requirements
  apt:
    pkg:
      - build-essential
      - libssl-dev
      - pkg-config
    state: present
- name: clone ipfs-sniffer
  git:
    dest: "{{ sniffer_build }}"
    repo: https://github.com/ipfs-search/ipfs-sniffer.git
    version: "{{ sniffer_version }}"
  register: source
  become: false
- block:
  - name: Ensure golang's available for building
    include_role:
      name: golang
      public: yes
  - block:
    - name: go get
      command:
        cmd: go get -tags=openssl
        chdir: "{{ sniffer_build }}"
    - name: go build
      command:
        cmd: go build -tags=openssl -o ipfs-sniffer
        chdir: "{{ sniffer_build }}"
    environment:
      PATH: "{{ golang_install_dir }}/bin:{{ ansible_env.PATH }}"
    become: false
  - name: Install ipfs-sniffer
    copy:
      src: "{{ sniffer_build }}/ipfs-sniffer"
      dest: "{{ sniffer_binary }}"
      remote_src: True
      mode: 775
    become: true
    notify: restart sniffer
  - include_role:
      name: annotate
    vars:
      role: sniffer
      version: "{{ source.after }}"
      action: upgrade
  when: source.changed
- group: name=ipfs-sniffer system=true state=present
- user: name=ipfs-sniffer group=ipfs-sniffer system=true state=present home="{{ sniffer_home }}" shell=/usr/sbin/nologin
- file: path="{{ sniffer_home }}" owner=ipfs-sniffer group=ipfs-sniffer mode=750 state=directory
- name: Configure service
  template: src=ipfs-sniffer.service dest=/etc/systemd/system/ipfs-sniffer.service
  notify: restart sniffer
- name: Enable service
  systemd: name=ipfs-sniffer daemon_reload=yes state=started enabled=yes
