---
- name: "Check for netplan"
  command: netplan --help
  ignore_errors: yes
  register: netplan_exists
- import_tasks: netplan.yml
  when: not netplan_exists.failed
# Ubuntu < 18.04
- import_tasks: interfaces.yml
  when: netplan_exists.failed
