---
tika_extractor_path: /usr/local/libexec
tika_extractor_version: "1.1"
tika_extractor_sha256: cb8237013f8e2de9d2efd23d04c2392c640476e805493a6939b89ef89ad05b6d
tika_extractor_url: "https://github.com/ipfs-search/tika-extractor/releases/download/v{{ tika_extractor_version }}/tika-extractor-{{ tika_extractor_version }}-runner.jar"
tika_extractor_heap_max: 3072m
tika_extractor_jar: tika-runner.jar
