---
- name: Install repository key
  apt_key: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc state=present id=6026DFCA
- name: Add repository
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present update_cache=yes
- name: Install required packages
  apt: pkg=rabbitmq-server state=latest
  notify: restart rabbitmq
- name: Configuration file
  template: src=rabbitmq.config dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq
- name: Enable required services
  service: name=rabbitmq-server enabled=yes state=started
- name: Setup rabbitmq admin user
  rabbitmq_user: user=admin
                 password=admin
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
                 tags=administrator
  notify: restart rabbitmq
- name: Enable rabbitmq plugins
  rabbitmq_plugin: names=rabbitmq_management,rabbitmq_shovel,rabbitmq_shovel_management state=enabled
  notify: restart rabbitmq
