---
- name: Install nginx configuration
  template:
    src: nginx-frontend.conf.j2
    dest: /etc/nginx/sites-available/frontend.conf
    mode: 0644
  notify: Reload nginx
- name: Enable nginx configuration
  file:
    path: /etc/nginx/sites-enabled/frontend.conf
    src: /etc/nginx/sites-available/frontend.conf
    state: link
  notify: Reload nginx
- name: Create cache directory
  file:
    path: "{{ frontend_cache_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
- name: Flush handlers
  meta: flush_handlers
- name: Ensure HTTP and HTTPS are listening
  wait_for:
    port: "{{ item }}"
  loop:
    - 80
    - 443
  timeout: 30
- name: Test API call
  uri:
    url: "https://{{ api_server_name }}/v1/search?q=test"
