---
- name: Gather facts from backend nodes
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  when: hostvars[item]['ansible_default_ipv4'] is not defined
  loop: "{{ groups['backend'] }}"
  ignore_unreachable: true
- name: Install nginx configuration
  template:
    src: nginx-frontend.conf
    dest: /etc/nginx/sites-available/frontend.conf
    mode: 0644
  notify: reload nginx
- name: Enable nginx configuration
  file:
    path: /etc/nginx/sites-enabled/frontend.conf
    src: /etc/nginx/sites-available/frontend.conf
    state: link
  notify: reload nginx
