---
- name: Gather facts from backend nodes
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  when: hostvars[item]['ansible_default_ipv4'] is not defined
  with_items: "{{ groups['index'] }}"
  ignore_unreachable: yes
- name: Install nginx configuration
  template:
    src: nginx-frontend.conf
    dest: /etc/nginx/sites-available/frontend.conf
    mode: 0644
  notify: restart nginx
- name: Enable nginx configuration
  file:
    path: /etc/nginx/sites-enabled/frontend.conf
    src: /etc/nginx/sites-available/frontend.conf
    state: link
  notify: restart nginx
