---
- name: CIFS utils
  apt:
    name: cifs-utils
    state: present
- name: Credentials file
  template:
    src: credentials.txt
    dest: "{{ storagebox_credentials_file }}"
    owner: root
    group: root
    mode: '0600'
- name: Create group
  group:
    name: "{{ storagebox_mountpoint_group }}"
    state: present
- name: Create mountpoint
  file:
    path: "{{ storagebox_mountpoint }}"
    state: directory
    owner: "{{ storagebox_mountpoint_owner }}"
    group: "{{ storagebox_mountpoint_group }}"
    mode: "{{ storagebox_mountpoint_directory_mode }}"
- name: Mount storagebox
  mount:
    fstype: cifs
    opts: "iocharset=utf8,rw,cache=strict,noexec,nosuid,nodev,uid={{ storagebox_mountpoint_owner }},gid={{ storagebox_mountpoint_group }},file_mode={{ storagebox_mountpoint_file_mode }},dir_mode={{ storagebox_mountpoint_directory_mode }},credentials={{ storagebox_credentials_file }}"
    src: "//{{ storagebox_username }}.your-storagebox.de/backup"
    path: "{{ storagebox_mountpoint }}"
    state: mounted
