---
- name: Set 127.0.0.1 in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 {{ fqdn }} {{ hostname }} localhost"
    state: present
    mode: 0644
  notify:
    - Restart systemd-logind
- name: Set ::1 in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^::1"
    line: "::1 {{ fqdn }} {{ hostname }} localhost"
    state: present
    mode: 0644
  notify:
    - Restart systemd-logind
  when: ansible_default_ipv6
- name: Set default IPv4 in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ipv4_address }}"
    line: "{{ ipv4_address }} {{ fqdn }} {{ hostname }} localhost"
    state: present
    mode: 0644
  notify:
    - Restart systemd-logind
- name: Set default IPv6 in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ipv6_address }}"
    line: "{{ ipv6_address }} {{ fqdn }} {{ hostname }} localhost"
    state: present
    mode: 0644
  notify:
    - Restart systemd-logind
  when: ansible_default_ipv6
- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  notify:
    - Restart systemd-logind
- name: Re-gather facts
  action: setup
  when: ansible_hostname != fqdn
