---
# Workaround: https://stackoverflow.com/questions/33563425/ansible-1-9-4-failed-to-lock-apt-for-exclusive-operation/40933352
- name: Ensure apt list dir exists
  file:
    path: /var/lib/apt/lists/
    state: directory
    mode: 0755

- name: Full (unsafe) upgrade of packages
  apt:
    update_cache: yes
    upgrade: full
    autoremove: yes
    autoclean: yes
  notify:
    - Reboot
