---
- name: build requirements
  apt:
    pkg:
      - build-essential
      - libssl-dev
      - pkg-config
    state: present
- name: clone ipfs-search
  git:
    dest: "{{ crawler_build }}"
    repo: https://github.com/ipfs-search/ipfs-search.git
    version: "{{ crawler_version }}"
  register: source
  become: false
- block:
  - name: Ensure golang's available for building
    include_role:
      name: golang
      public: yes
  - block:
    - name: go get
      command:
        cmd: go get ./...
        chdir: "{{ crawler_build }}"
    - name: go build
      command:
        cmd: go build -o ipfs-crawler
        chdir: "{{ crawler_build }}"
    - name: Install ipfs-crawler
      copy:
        src: "{{ crawler_build }}/ipfs-crawler"
        dest: "{{ crawler_binary }}"
        remote_src: True
        mode: 0755
      become: true
      notify: restart ipfs-crawler
    - include_role:
        name: annotate
      vars:
        role: crawler
        version: "{{ source.after }}"
        action: upgrade
    environment:
      PATH: "{{ golang_install_dir }}/bin:{{ ansible_env.PATH }}"
    become: false
  when: source.changed
- group: name=ipfs-crawler system=true state=present
- user: name=ipfs-crawler comment="ipfs-crawler daemon" group=ipfs-crawler system=true state=present home=/nonexistent shell=/usr/sbin/nologin
- name: Install crawler systemd service
  template: src=ipfs-crawler.service dest=/etc/systemd/system/ipfs-crawler.service
  notify: restart ipfs-crawler
- name: Ensures ipfs-search dir exists
  file: path=/etc/ipfs-crawler state=directory
- name: Loading secrets
  include_vars:
    file: ../../vault/secrets.yml
- name: Install configuration file
  template: src=config.yml dest=/etc/ipfs-crawler/config.yml
  notify:
    - restart ipfs-crawler
- service: name=ipfs-crawler enabled=yes state=started
