---

- name: Add OpenJDK PPA
  apt_repository:
    repo: ppa:openjdk-r/ppa
    state: present
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] != "20"
- name: Install OpenJDK
  apt:
    name: openjdk-11-jre-headless
    state: latest
