---
- name: Presence of user {{ account.key }}
  user:
    name: "{{ account.key }}"
    shell: /bin/bash
    state: present

- name: SSH public key(s) for {{ account.key }}
  authorized_key:
    user: "{{ account.key }}"
    key: "{{ account.value | join('\n') }}"
    exclusive: True

- name: "User in sudoers {{ account.key }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ account.key }}"
    line: "{{ account.key }} ALL=(ALL:ALL) NOPASSWD: ALL"
    state: present
