---
- name: Create loki user
  user:
    name: loki
    create_home: false

- name: Create conf directory
  file:
    state: directory
    path: /etc/loki
    mode: '0755'
    group: loki
    owner: loki

- name: Create data directory
  file:
    state: directory
    path: "{{ loki_data_path }}"
    mode: '0755'
    group: loki
    owner: loki

- name: Download binary
  get_url:
    url: https://github.com/grafana/loki/releases/download/{{ loki_version }}/loki-linux-amd64.zip
    dest: /tmp/loki-linux-amd64.zip
    checksum: sha256:{{ loki_download_sha256 }}
  register: loki_download

- name: Unarchive
  unarchive:
    src: /opt/loki-linux-amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: loki
    group: loki
  when: loki_download.changed
  notify: restart loki

- name: binary file permission
  file:
    path: /usr/local/bin/loki-linux-amd64
    owner: loki
    group: loki

- name: systemd unit
  template:
    src: loki.service
    dest: /etc/systemd/system/loki.service
    mode: 0644
  notify: restart loki

- name: config file
  template:
    src: config.yaml
    dest: /etc/loki/config.yaml
    mode: 0644
  notify: restart loki

- name: service enabled
  systemd:
    daemon_reload: yes
    name: loki
    enabled: yes
    state: started

# - name: Setup Datasource for loki
#   community.grafana.grafana_datasource:
#     name: Loki
#     grafana_url: "http://{{ monitoring_host_internal_addr }}:3000"
#     grafana_user: admin
#     grafana_password: "{{ grafana_password }}"
#     ds_type: loki
#     ds_url: "http://{{ monitoring_host_internal_addr }}:3100"

#- name: Setup Datasource for influxDB
#  community.grafana.grafana_datasource:
#    name: influxDB
#    grafana_url: "http://{{ monitoring_host_internal_addr }}:3000"
#    grafana_user: admin
#    grafana_password: "{{ grafana_password }}"
#    ds_type: influxdb
#    ds_url: "http://{{ monitoring_host_internal_addr }}:8086"
