---
- name: Install Golang, GIT
  apt: name={{item}} state=installed
  with_items:
       - golang-go
       - git
  become: true
- block:
  - file: path="/home/vagrant/gocode" state=directory user=vagrant group=vagrant
  - command: go get .
    args:
      chdir: /vagrant
