ipfs:
  api_url: http://localhost:5001
  gateway_url: http://localhost:8080
  partial_size: 256KB
elasticsearch:
  url: http://localhost:9200
amqp:
  url: amqp://guest:guest@localhost:5672/
  max_reconnect: 100
  reconnect_time: 2s
tika:
  url: http://localhost:8231
  timeout: 5m
  max_file_size: 4GB
instrumentation:
  sampling_ratio: 0.01
  jaeger_endpoint: http://localhost:14268/api/traces
crawler:
  direntry_buffer_size: 8192
  min_update_age: 2m
  stat_timeout: 2m
  direntry_timeout: 2m
  max_dirsize: 32768
sniffer:
  lastseen_expiration: 1h
  lastseen_prunelen: 32768
  logger_timeout: 1m
  buffer_size: 512
indexes:
  files:
    name: ipfs_files
  directories:
    name: ipfs_directories
  invalids:
    name: ipfs_invalids
queues:
  files:
    name: files
  directories:
    name: directories
  hashes:
    name: hashes
workers:
  hash_workers: 500
  file_workers: 50
  directory_workers: 5
