ipfs:
  api_url: http://localhost:5001
  gateway_url: http://localhost:8080
  partial_size: 256KB
elasticsearch:
  url: http://localhost:9200
amqp:
  url: "amqp://admin:admin@{{ hostvars[groups['rabbitmq'][0]].vlan_ip | ipaddr('address') }}:5672/"
  max_reconnect: 100
  reconnect_time: 2s
  message_ttl: {{ amqp_message_ttl }}
tika:
  url: http://localhost:8081
  timeout: 5m
  max_file_size: 4GB
instrumentation:
  sampling_ratio: 0.01
  jaeger_endpoint: http://localhost:14268/api/traces
crawler:
  direntry_buffer_size: 8192
  min_update_age: 12h
  stat_timeout: 13s
  direntry_timeout: 13s
  max_dirsize: 32768
sniffer:
  lastseen_expiration: 1h
  lastseen_prunelen: 65536
  logger_timeout: 1m
  buffer_size: 512
indexes:
  files:
    name: ipfs_files
  directories:
    name: ipfs_directories
  invalids:
    name: ipfs_invalids
  partials:
    name: ipfs_partials
queues:
  files:
    name: files
  directories:
    name: directories
  hashes:
    name: hashes
workers:
  hash_workers: {{ crawler_hash_workers }}
  file_workers: {{ crawler_file_workers }}
  directory_workers: {{ crawler_directory_workers }}
