---
- name: Install vlan package
  apt:
    pkg: vlan
- name: Configure interfaces file
  template:
    src: vlan.j2
    dest: "/etc/network/interfaces.d/{{ vlan_iface }}.{{ vlan_id }}"
    mode: 0644
  register: vlan_config
  notify:
    - restart networking
- name: Ensure vlan interface started
  systemd:
    name: "ifup@{{ vlan_iface }}.{{ vlan_id }}"
    state: started
