auth_enabled: false

server:
  http_listen_address: {{ monitoring_host_internal_addr }}
  http_listen_port: 3100
  grpc_listen_port: 9096

compactor:
  working_directory: {{ loki_data_path }}/retention
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 20

common:
  path_prefix: {{ loki_data_path }}
  storage:
    filesystem:
      chunks_directory: {{ loki_data_path }}/chunks
      rules_directory: {{ loki_data_path }}/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

limits_config:
  # ingestion_rate_mb: 32
  # ingestion_burst_size_mb: 64
  # max_concurrent_tail_requests: 100
  # max_cache_freshness_per_query: 10m
  # max_streams_per_user: 100
  retention_period: 336h 
  # 2 weeks retention period

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
