---
- name: Create destination folder for search api
  file: path={{ nsfw_server_install_path }} state=directory owner="{{ lookup('env','USER') }}"
- block:
  - name: Clone nsfw-server repository
    git:
      dest: "{{ nsfw_server_install_path }}"
      repo: "{{ nsfw_server_repo }}"
      version: "{{ nsfw_server_version }}"
    register: source
  - name: Install search API
    command: npm install --production --no-save
    args:
      chdir: "{{ nsfw_server_install_path }}"
    when: source.changed
    notify: "restart {{ nsfw_server_service }}"
  - include_role:
      name: annotate
    vars:
      role: api
      version: "{{ source.after }}"
      action: upgrade
    when: source.changed
  become: false
- name: Create {{ nsfw_server_group }} group
  group:
    name: "{{ nsfw_server_group }}"
    system: true
    state: present
- name: Create {{ nsfw_server_user }} user
  user:
    name: "{{ nsfw_server_user}}"
    comment: nsfw-server
    group: "{{ nsfw_server_group }}"
    system: true
    state: present
    home: /nonexistent
    shell: /usr/sbin/nologin
- name: Install ipfs-search service
  template:
    src: nsfw-server.service
    dest: "/etc/systemd/system/{{ nsfw_server_service }}.service"
  notify: "restart {{ nsfw_server_service }}"
- name: Enable search service
  service:
    name: "{{ nsfw_server_service }}"
    enabled: yes
    state: started
