---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
- name: install apt upgrades
  apt: upgrade=dist
- name: install unattended upgrades
  apt: name=unattended-upgrades state=present
- name: enable unattended upgrades
  debconf: name=unattended-upgrades question=enable_auto_updates value=true vtype=boolean
- name: set timezone to Europe/Lisbon
  timezone: name=Europe/Lisbon
- name: Install misc utils
  apt: name={{item}} state=present
  with_items:
    - apt-transport-https
    - screen
    - tree
    - git
- name: Configure journald
  copy: dest=/etc/systemd/journald.conf src=journald.conf owner=root group=root mode=644
  notify: restart journald
- name: Install scripts
  copy: dest=/usr/local/ src=bin owner=root group=root mode=755
