# Expose elasticsearch to local (non-global) IP's
# network.host: [_site_, _local_]
path.repo: ["/var/lib/elasticsearch/backup"]
repositories.url.allowed_urls: ["http://localhost:8080/*"]
http.cors.enabled: true
http.cors.allow-origin: "chrome-extension://hkedbapjpblbodpgbajblpnlpenaebaa"
