---
- name: NodeJS API server and dependencies.
  hosts: index
  become: true
  roles:
    - role: vendor/nginx
      tags: ['nginx']
    - role: vendor/nodejs
      tags: ['nodejs']
    - role: services/api
      tags: ['api']
- import_playbook: nsfw_server.yml
