---
- name: NodeJS API server and dependencies.
  hosts: index
  become: true
  vars_files:
    - vars/common.yml
  roles:
    - role: vendor/nginx
      tags: ['nginx']
    - role: vendor/nodejs
      tags: ['nodejs']
    - role: services/nsfw_server
      tags: ['nsfw_server']
    - role: services/api
      tags: ['api']
