---
- name: Configure ipfs-search-api
  import_playbook: api_search.yml
- name: Configure NSFW server
  import_playbook: api_nsfw_server.yml
- name: Configure nyats (thumbnailer)
  import_playbook: api_nyats.yml
