---
- name: Search API
  hosts: search_api
  tags: ipfs-search-api
  become: true
  serial:
    - 1
    - "100%"
  roles:
    - name: Search API
      tags: node_server
      role: services/node_server
      vars:
        node_server_name: ipfs-search
        node_server_install_path: "/usr/local/libexec/ipfs-search/api"
        node_server_working_directory: "/usr/local/libexec/ipfs-search/api/server"
        node_server_repo: "https://github.com/ipfs-search/ipfs-search-api.git"
        node_server_version: "{{ ipfs_search_api_version }}"
        node_server_requires: opensearch.service
        node_server_port: "{{ ipfs_search_api_port }}"
        node_server_proxy_location_name: "99_ipfs-search.conf"
        node_server_proxy_location: "/v1/"
        node_server_proxy_root: "/"
