---
- name: Configure Elasticsearch.
  hosts: elasticsearch
  become: true
  serial: 1
  any_errors_fatal: true

  # NOTE: Comment out for clean installs!
  pre_tasks:
    - name: Ensure ES cluster health is green
      uri: url=http://localhost:9200/_cluster/health method=GET
      register: response
      until: "response.json.status == 'green'"
      retries: 1000
      delay: 2

  roles:
    - role: elasticsearch
      tags: ['elasticsearch']
      vars:
        oss_version: true
        es_plugins:
          - plugin: repository-s3
    - name: push logs files to loki using promtail
      role: vendor/promtail
      tags: promtail
      vars: 
        es_logs_to_loki: true
    - role: vendor/es_snapshots
      tags: ['snapshots']
    
