---
# Direct dependencies for crawling.
- hosts: index
  become: true
  vars_files:
    - vars/common.yml
  roles:
    - { name: tika-extractor, tags: ['tika-extractor'] }
    - { name: ipfs, tags: ['ipfs'] }
    - { name: crawler, tags: ['crawler'] }

