---
# Direct dependencies for crawling.
- hosts: index
  become: true
  vars_files:
    - vars/common.yml
  serial:
    - 1
    - "100%"
  roles:
    - { name: tika-extractor, tags: ['tika-extractor'] }
    - { name: nsfw_server, tags: ['nsfw_server']}
    - { name: ipfs, tags: ['ipfs'] }
    - { name: ipfs-gc, tags: ['ipfs-gc'] }
    - { name: crawler, tags: ['crawler'] }

