---
- name: Crawler and direct dependencies.
  hosts: index
  become: true
  serial:
    - 1
    - "100%"
  roles:
    - role: vendor/jre
      tags: ['jre']
    - role: services/tika-extractor
      tags: ['tika-extractor']
    - role: vendor/nodejs
      tags: ['nodejs']
    - role: services/crawler
      tags: ['crawler']
