---
- name: ipfs-gateway
  hosts: ipfs-gateway
  become: true
  roles:
    - role: vendor/ipfs
      tags: ipfs
    - role: vendor/ipfs-gc
      tags: ipfs-gc
    - role: vendor/nginx
      tags: nginx
    - role: vendor/ipfs-gateway
      tags: ipfs-gateway
      vars:
        ipfs_gateway_hostname: gw.dwebsearch.com
# - name: DNS
#   hosts: ipfs-gateway
#   tasks:
#     - name: A record for host
#       cloudflare_dns:
#         zone: "dwebsearch.com"
#         record: "gw"
#         type: CNAME
#         value: "eccles.dwebsearch.org"
#         api_token: "{{ cloudflare_token }}"
#       # when: ipv4_address != a_record
#       retries: 3
#       delay: 3
