---
# Common configuration for all hosts
- hosts: all,!poppycorn
  become: true
  strategy: free
  vars_files:
    - vars/common.yml
  roles:
    - role: telegraf
      tags: telegraf
    - name: promtail installation
      role: promtail
      tags: promtail
