---
- name: Common configuration for all hosts.
  hosts: all,!poppycorn
  become: true
  strategy: free
  roles:
    - role: vendor/telegraf
      tags: telegraf
    - role: vendor/promtail
      tags: promtail
