---
- name: Infrastructure for observability.
  hosts: stats
  become: true
  vars:
    influxdb2_http_bind_address: "{{ vlan_ip | ipaddr('address')}}:8086"
  roles:
    - role: vendor/influxdb2
      tags: influxdb
    # - { name: storagebox, tags: ['storagebox'] }
    # - { name: influxdb_backup, tags: influxdb_backup }
    - role: vendor/grafana
      tags: grafana
    - role: vendor/loki
      tags: loki
    - role: vendor/tempo
      tags: tempo
