---

- name: opensearch installation & configuration
  hosts: opensearch
  tags: opensearch
  gather_facts: true
  roles:
    - { role: vendor/opensearch }

- name: opensearch dashboards installation & configuration
  hosts: opensearch_dashboards
  tags: dashboards
  gather_facts: true
  roles:
    - { role: vendor/opensearch-dashboards }
