---
- name: Disable crawler
  hosts: index
  become: true
  gather_facts: false
  tags: shutdown
  tasks:
    - name: Stop crawler
      service:
        name: ipfs-crawler
        state: stopped
      ignore_errors: true
- name: Perform rolling upgrade on index (data) nodes
  hosts: opensearch:!master
  become: true
  serial: 1
  any_errors_fatal: true
  vars:
    required_nodes: "{{ groups['opensearch'] | length }}"
    required_version: "{{ os_version }}" # Note: currently unused.
  roles:
    - role: vendor/opensearch_rolling_upgrade
      tags: rolling-upgrade
- name: Perform rolling upgrade on master nodes
  hosts: master
  become: true
  serial: 1
  any_errors_fatal: true
  vars:
    required_nodes: "{{ groups['opensearch'] | length }}"
    required_version: "{{ os_version }}" # Note: currently unused.
  roles:
    - role: vendor/opensearch_rolling_upgrade
      tags: rolling-upgrade
- name: Re-enable crawler
  hosts: index
  become: true
  tags: restart
  tasks:
    - name: Start crawler
      service:
        name: ipfs-crawler
        state: started
