---

- name: opensearch installation & configuration
  hosts: os-cluster
  tags: opensearch
  gather_facts: true
  roles:
    - { role: vendor/opensearch }

- name: opensearch dashboards installation & configuration
  hosts: os-dashboards
  tags: dashboards
  gather_facts: true
  roles:
    - { role: vendor/opensearch-dashboards }
