---
- hosts: all
  become: true
  vars_files:
    - vars/common.yml
  roles:
    - role: common
      tags: ['common']
    - role: setup/hostname
      tags: ['hostname']
    - role: setup/unattended_upgrades
      tags: ['unattended_upgrades']
    - role: setup/cgconfig
      tags: ['cgconfig']
    - role: setup/firewall
      tags: ['firewall']
    - role: vendor/jre
      tags: ['jre']
- hosts: dmz
  become: true
  roles:
    - role: setup/vlan
      tags: ['vlan']
- import_playbook: monitoring.yml
