# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook setup_hetzner.yml -l new
# WIP
# - name: Setup reverse DNS
#   hosts: all
#   roles:
#     - { name: hetzner_reverse_dns, tags: [hetzner_reverse_dns] }
# Swithc work is WIP
# - name: Add server to switch
#   hosts: all
#   tags: add_to_switch
#   roles:
#     - hetzner_add_to_switch
- name: Install OS image
  hosts: all # TODO: Filter by machines in rescue mode
  remote_user: root
  ignore_unreachable: true
  roles:
    - role: setup/hetzner_install_image
      tags: install_image
    - role: setup/update_ssh_hostkeys
      tags: update_ssh_hostkeys
