---
- name: Common server setup.
  hosts: all
  become: true
  roles:
    - role: setup/common
      tags: ['common']
    - role: setup/hostname
      tags: ['hostname']
    - role: setup/unattended_upgrades
      tags: ['unattended_upgrades']
- name: cgconfig and firewall
  hosts: all:!hcloud
  become: true
  roles:
    - role: setup/cgconfig
      tags: ['cgconfig']
    - role: setup/firewall
      tags: ['firewall']
- hosts: dmz:!hcloud
  become: true
  roles:
    - role: setup/vlan
      tags: ['vlan']
- import_playbook: monitoring.yml
