---
- hosts: all
  become: true
  vars_files:
    - vars/common.yml
  roles:
    - { name: common, tags: ['common'] }
    - { name: hostname, tags: ['hostname']}
    - { name: unattended_upgrades, tags: ['upgrades']}
    - role: cgconfig
      tags: ['cgconfig']
    - { name: firewall, tags: ['firewall']}
    - { name: jre, tags: ['jre']}
- hosts: dmz
  become: true
  roles:
    - role: vlan
      tags: ['vlan']
- import_playbook: monitoring.yml
