# ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook setup_hetzner.yml -l new
# Swithc work is WIP
# - name: Add server to switch
#   hosts: all
#   tags: add_to_switch
#   roles:
#     - hetzner_add_to_switch
- name: Restart host in rescue mode
  hosts: hetzner
  remote_user: root
  gather_facts: false
  ignore_unreachable: true
  roles:
    - role: setup/hetzner_rescue
      tags: rescue
    - role: setup/update_ssh_hostkeys
      tags: update_ssh_hostkeys
- name: Install OS image
  hosts: hetzner
  remote_user: root
  ignore_unreachable: true
  roles:
    - role: setup/hetzner_install_image
      tags: install_image
    - role: setup/update_ssh_hostkeys
      tags: update_ssh_hostkeys
