---
- name: Generate hostnames
  hosts: nameless
  gather_facts: false
  vars_files:
    # `JSON.stringify(Array.from(document.querySelectorAll("#mw-content-text > div.mw-parser-output > table > tbody > tr > td:nth-child(2)")).map(e => e.innerText.split(",", 1)[0].toLowerCase() + '.ipfs-search.com'));`
    - group_vars/new_hostnames.json
  roles:
    - role: setup/generate_hostnames
      tags: 'generate_hostnames'
- name: Create group of hosts without VLAN IP
  hosts: dmz
  gather_facts: false
  tags: generate_vlan_ip
  tasks:
  - name: Create group for VLAN-less hosts
    group_by:
      key: "{% if vlan_ip is defined %}vlanip{% else %}novlanip{% endif %}"
- name: Generate VLAN IP's
  hosts: novlanip
  gather_facts: false
  tags: generate_vlan_ip
  roles:
    - role: setup/generate_vlan_ip
- name: Configure DNS
  hosts: all
  tags: dns
  gather_facts: true
  roles:
    - role: setup/cloudflare_dns
      tags: dns
- name: Configure Hetzner robot reverse DNS
  hosts: hetzner
  tags: reverse_dns
  gather_facts: true
  roles:
    - role: setup/hetzner_robot_reverse_dns
# TODO: Hcloud reverse DNS
