---
- name: Generate hostnames
  hosts: nameless
  gather_facts: false
  vars_files:
    # `JSON.stringify(Array.from(document.querySelectorAll("#mw-content-text > div.mw-parser-output > table > tbody > tr > td:nth-child(2)")).map(e => e.innerText.split(",", 1)[0].toLowerCase() + '.ipfs-search.com'));`
    - ../../group_vars/new_hostnames.json
  roles:
    - role: setup/generate_hostnames
      tags: 'generate_hostnames'
- name: Create group of hosts without VLAN IP
  hosts: dmz
  gather_facts: false
  tags: generate_vlan_ip
  tasks:
  - name: Create group for VLAN-less hosts
    group_by:
      key: "{% if vlan_ip is defined %}vlanip{% else %}novlanip{% endif %}"
- name: Generate VLAN IP's
  hosts: novlanip
  gather_facts: false
  tags: generate_vlan_ip
  roles:
    - role: setup/generate_vlan_ip
- name: Create group of hosts without IPFS peer id
  hosts: ipfs
  gather_facts: false
  tags: generate_ipfs_key
  tasks:
  - name: Create group for VLAN-less hosts
    group_by:
      key: "{% if ipfs_peer_id is defined %}hasipfspeerid{% else %}noipfspeerid{% endif %}"
- name: Generate IPFS keys
  hosts: noipfspeerid
  gather_facts: false
  tags: generate_ipfs_key
  roles:
    - role: setup/generate_ipfs_key
- name: Explicitly gather facts
  hosts: all
  gather_facts: false
  tags:
    - dns
    - reverse_dns
  tasks:
    - setup:
- name: Configure DNS
  hosts: all
  roles:
    - role: setup/cloudflare_dns
      tags: dns
    - role: setup/hetzner_reverse_dns
      tags: reverse_dns
