---
- name: Generate hostnames
  delegate_to: localhost
  block:
  - name: Get available hostnames in randomized order
    set_fact:
      available_hostnames: "{{ new_hostnames | unique | difference(groups['all']) | shuffle }}"
    run_once: True
  - name: Assert enough hostnames available
    assert:
      that: available_hostnames | count() >= ansible_play_hosts | count()
      fail_msg: "Not enough hostnames available: {{ available_hostnames | count() }} available, {{ ansible_play_hosts | count() }} required."
    run_once: True
  - name: Pick unique hostname
    set_fact:
      picked_hostname: "{{ available_hostnames[ansible_play_batch.index(inventory_hostname)] }}"
  - name: Print generated hostname
    debug:
      var: picked_hostname
  - name: Set server names through Hetzner
    uri:
      url: "https://robot-ws.your-server.de/server/{{ hrobot_server_number }}"
      url_username: "{{ hetzner_user }}"
      url_password: "{{ hetzner_password }}"
      body_format: form-urlencoded
      method: POST
      body:
        server_name: "{{ picked_hostname }}"
    when: hrobot_server_name != picked_hostname
  - name: Refresh inventory to ensure new hostnames exist in inventory
    meta: refresh_inventory
