---
- name: Get host index
  set_fact:
    host_index: "{{ groups['dmz'].index(inventory_hostname) }}"
  run_once: true
  delegate_to: localhost
- block:
  - name: Generate vlan_ip
    set_fact:
      generated_vlan_ip: true
      # Add subnet
      vlan_ip: "{{ vlan_subnet | ansible.netcommon.ipaddr(host_index) }}"
  delegate_to: localhost
  when: vlan_ip is undefined
- block:
  - name: Print IP's
    debug:
      var: vlan_ip
  - name: Add IP's to host_vars
    lineinfile:
      create: true
      path: "{{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml"
      regexp: '^vlan_ip'
      line: "vlan_ip: {{ vlan_ip }}"
  delegate_to: localhost
  when: generated_vlan_ip is defined and generated_vlan_ip

