---
- name: Install apt-transport-https
  apt: name=apt-transport-https state=present
- name: Install ca-certificates
  apt: name=ca-certificates state=latest
- name: Install InfluxDB repository key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present
- name: Add Telegraf repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_lsb.codename }} stable"
    filename: "telegraf"
    state: present
- name: Install packages
  apt:
    pkg: telegraf
    state: present
- block:
    - name: Install lm-sensors package
      apt:
        pkg: lm-sensors
        state: present
    - name: Configure sensor-modules
      template:
        src: sensors.conf
        dest: /etc/modules-load.d/sensors.conf
      register: sensors
      when: sensor_modules is defined
    - systemd:
        service: systemd-modules-load
        state: restarted
      when: sensors.changed
    - systemd:
        service: lm-sensors
        enabled: yes
        state: started
  when: has_sensors is defined
- name: Install Telegraf package
  apt:
    name: telegraf
    state: present
    update_cache: yes
  notify: restart telegraf
- name: Telegraf configuration
  template: src=telegraf.conf dest=/etc/telegraf/telegraf.conf
  notify: restart telegraf
- name: Enable telegraf service
  service: name=telegraf enabled=yes state=started

