---
- name: Set A and AAAA records
  delegate_to: localhost
  block:
  - name: Get existing records
    set_fact:
      a_record: "{{ lookup('dig', hostname + '.' + domain_name + './A') }}"
      aaaa_record: "{{ lookup('dig', hostname + '.' + domain_name + './AAAA') }}"
  - name: A record for host
    cloudflare_dns:
      zone: "{{ domain_name }}"
      record: "{{ hostname }}"
      type: A
      value: "{{ ipv4_address }}"
      api_token: "{{ cloudflare_token }}"
    when: ipv4_address != a_record
    retries: 3
    delay: 3
  - name: AAAA record for host
    cloudflare_dns:
      zone: "{{ domain_name }}"
      record: "{{ hostname }}"
      type: AAAA
      value: "{{ ipv6_address }}"
      api_token: "{{ cloudflare_token }}"
    when: ipv6_address != aaaa_record
    retries: 3
    delay: 3
